export function renderColorPicker(draft, escapeText) {
  return `<div class="modal-backdrop color-picker-backdrop"><form class="modal color-picker-modal" id="color-form">
    <button type="button" class="modal-close" data-action="close" aria-label="Cerrar">×</button>
    <p class="eyebrow">COLOR PERSONALIZADO</p><h2>Elige tu color</h2>
    <label class="custom-color-name">Nombre<input id="custom-color-name" maxlength="30" value="${escapeText(draft.name)}" placeholder="Ej. Azul océano" /></label>
    <div class="color-picker-body"><div class="spectrum-wrap"><div class="color-spectrum" id="color-spectrum" style="--picker-hue:${draft.hue}deg;--picker-saturation:${draft.saturation}%;--picker-brightness:${draft.brightness}%" role="slider" tabindex="0" aria-label="Tabla cromática; mueve el puntero para elegir intensidad y brillo"><i id="spectrum-cursor" style="left:${draft.saturation}%;top:${100 - draft.brightness}%"></i></div><div class="hue-track"><input id="color-hue" type="range" min="0" max="359" value="${draft.hue}" aria-label="Matiz"/><span>Matiz</span></div></div>
      <div class="color-adjustments"><div class="color-preview-large" id="color-preview-large" style="--preview-color:${draft.hex}"></div><div class="color-values"><label>HEX<input id="color-hex" value="${draft.hex}" maxlength="7" /></label><label>R<input id="color-red" inputmode="numeric" maxlength="3" /></label><label>G<input id="color-green" inputmode="numeric" maxlength="3" /></label><label>B<input id="color-blue" inputmode="numeric" maxlength="3" /></label></div><label class="color-range-label">Intensidad <output id="color-saturation-value">${Math.round(draft.saturation)}%</output><input id="color-saturation" type="range" min="0" max="100" value="${draft.saturation}" /></label><label class="color-range-label">Brillo <output id="color-brightness-value">${Math.round(draft.brightness)}%</output><input id="color-brightness" type="range" min="0" max="100" value="${draft.brightness}" /></label></div></div>
    <div class="color-source-tools"><button type="button" class="button secondary" data-action="eyedropper">◎ Cuentagotas de pantalla</button><button type="button" class="button secondary" data-action="sample-image">▧ Tomar de imagen</button><input id="sample-image-file" type="file" accept="image/*" hidden /></div>
    <div class="sampled-image-wrap" id="sampled-image-wrap" hidden><p>Haz clic sobre el punto de la imagen que quieras muestrear.</p><canvas id="sampled-image"></canvas></div>
    <p class="color-picker-note" id="eyedropper-note"></p>
    <div class="color-picker-actions"><button type="button" class="button secondary" data-action="close">Cancelar</button><button type="submit" class="button primary">Seleccionar color</button></div>
  </form></div>`;
}
