import { COLOR_CATEGORIES, PRESET_COLORS } from '../../domain/pattern/ColorCatalog.js';

export function renderPalettePanel(pattern, selected, group, view, maxDimension, escapeText) {
  const active = pattern.palette[selected]?.id;
  const personal = pattern.palette.map((color, index) => ({ ...color, index })).filter(color => color.source === 'custom');
  const swatches = group === 'presets'
    ? PRESET_COLORS.map(color => `<button class="color-swatch" data-preset="${color.id}" data-category="${color.category}" data-name="${escapeText(color.name).toLowerCase()}" aria-label="${escapeText(color.name)} ${color.hex}" title="${escapeText(color.name)} · ${color.hex}"><i style="--swatch:${color.hex}"></i><span>${escapeText(color.name)}</span>${active === color.id ? '<b>✓</b>' : ''}</button>`).join('')
    : personal.map(color => `<button class="color-swatch personal-swatch ${active === color.id ? 'selected' : ''}" data-color="${color.index}" data-category="Personalizados" data-name="${escapeText(color.name).toLowerCase()}" aria-label="${escapeText(color.name)} ${color.hex}" title="${escapeText(color.name)} · ${color.hex}"><i style="--swatch:${color.hex}"></i><span>${escapeText(color.name)}</span><small>${pattern.cells.filter(cell => cell === color.id).length}</small></button>`).join('');
  const categoryOptions = ['Todos', ...COLOR_CATEGORIES].map(category => `<option value="${category}">${category}</option>`).join('');
  return `<aside class="palette-panel">
    <div class="palette-heading"><div><p class="panel-label">PALETA DE COLORES</p><span>Elige un color para pintar</span></div><div class="palette-view-toggle" aria-label="Vista de colores"><button type="button" data-action="palette-view" data-view="grid" class="${view === 'grid' ? 'active' : ''}" aria-label="Vista en cuadrícula" title="Cuadrícula">▦</button><button type="button" data-action="palette-view" data-view="list" class="${view === 'list' ? 'active' : ''}" aria-label="Vista en lista" title="Lista">☷</button></div></div>
    <div class="palette-groups" role="tablist" aria-label="Grupos de colores"><button type="button" data-action="palette-group" data-group="presets" class="${group === 'presets' ? 'active' : ''}" role="tab" aria-selected="${group === 'presets'}">Predeterminados <small>${PRESET_COLORS.length}</small></button><button type="button" data-action="palette-group" data-group="custom" class="${group === 'custom' ? 'active' : ''}" role="tab" aria-selected="${group === 'custom'}">Personalizados <small>${personal.length}</small></button></div>
    <div class="palette-filters"><label class="palette-search"><span aria-hidden="true">⌕</span><input id="palette-search" type="search" placeholder="Buscar color..." aria-label="Buscar color" /></label><select id="palette-category" aria-label="Filtrar por grupo" ${group === 'custom' ? 'hidden' : ''}>${categoryOptions}</select></div>
    ${group === 'custom' ? '<button type="button" class="button secondary full color-create-button" data-action="select-color">＋ Seleccionar color</button>' : ''}
    <div class="palette-swatches ${view}" role="listbox" aria-label="${group === 'custom' ? 'Colores personalizados' : 'Colores predeterminados'}">${swatches || (group === 'custom' ? '<p class="palette-empty">Aún no has creado colores. Pulsa “Seleccionar color” para añadir uno.</p>' : '')}</div>
    ${group === 'presets' ? '<button type="button" class="text-button color-create-link" data-action="select-color">＋ Crear color personalizado</button>' : ''}
    <div class="properties"><p class="panel-label">TAMAÑO DEL PATRÓN</p><div class="size-row"><label>Ancho<input id="resize-width" type="number" min="1" max="${maxDimension}" value="${pattern.width}" /></label><label>Largo<input id="resize-height" type="number" min="1" max="${maxDimension}" value="${pattern.height}" /></label></div><button class="button secondary full" data-action="resize">Aplicar tamaño</button><p class="hint">Reducir el patrón puede eliminar mostacillas del área recortada.</p></div>
  </aside>`;
}
