import { BASIC_COLORS, COLOR_CATEGORIES, PRESET_COLORS } from '../../domain/pattern/ColorCatalog.js';

export function renderPalettePanel(pattern, selected, group, view, maxDimension, escapeText, collapsed = false, category = 'Todos', query = '', categoryOpen = false) {
  const active = pattern.palette[selected]?.id;
  const legacyIds = new Set(['rose', 'blue', 'gold', 'plum', 'cream']);
  const presetIds = new Set(PRESET_COLORS.map(color => color.id));
  const personal = pattern.palette.map((color, index) => ({ ...color, index })).filter(color => color.source === 'custom' || (!presetIds.has(color.id) && !legacyIds.has(color.id)));
  const legacyPresets = pattern.palette.map((color, index) => ({ ...color, index })).filter(color => legacyIds.has(color.id));
  const presetSwatch = color => `<button class="color-swatch ${active === color.id ? 'selected' : ''}" data-preset="${color.id}" data-category="${escapeText(color.category)}" data-name="${escapeText(color.name.toLowerCase())}" data-search="${escapeText(`${color.name} ${color.hex} ${color.category}`.toLowerCase())}" aria-label="${escapeText(color.name)} ${color.hex}" title="${escapeText(color.name)} · ${color.hex}"><i style="--swatch:${color.hex}"></i><span>${escapeText(color.name)}</span>${active === color.id ? '<b>✓</b>' : ''}</button>`;
  const personalSwatch = color => `<button class="color-swatch personal-swatch ${active === color.id ? 'selected' : ''}" data-color="${color.index}" data-category="Personalizados" data-name="${escapeText(color.name.toLowerCase())}" data-search="${escapeText(`${color.name} ${color.hex} Personalizados`.toLowerCase())}" aria-label="${escapeText(color.name)} ${color.hex}" title="${escapeText(color.name)} · ${color.hex}"><i style="--swatch:${color.hex}"></i><span>${escapeText(color.name)}</span><small>${pattern.cells.filter(cell => cell === color.id).length}</small></button>`;
  const swatches = group === 'basics'
    ? BASIC_COLORS.map(presetSwatch).join('')
    : group === 'presets'
      ? [...legacyPresets.map(color => ({ ...color, category: 'Neutros', index: color.index })), ...PRESET_COLORS].map(color => color.index == null ? presetSwatch(color) : `<button class="color-swatch ${active === color.id ? 'selected' : ''}" data-color="${color.index}" data-category="Neutros" data-name="${escapeText(color.name.toLowerCase())}" data-search="${escapeText(`${color.name} ${color.hex} Neutros`.toLowerCase())}" aria-label="${escapeText(color.name)} ${color.hex}" title="${escapeText(color.name)} · ${color.hex}"><i style="--swatch:${color.hex}"></i><span>${escapeText(color.name)}</span>${active === color.id ? '<b>✓</b>' : ''}</button>`).join('')
      : personal.map(personalSwatch).join('');
  const categoryOptions = ['Todos', ...COLOR_CATEGORIES].map(option => `<button type="button" role="option" aria-selected="${category === option}" data-action="palette-category" data-category="${escapeText(option)}" class="palette-category-option ${category === option ? 'active' : ''}">${escapeText(option)}</button>`).join('');
  return `<aside class="palette-panel ${collapsed ? 'is-collapsed' : ''}">
    <button type="button" class="palette-collapse" data-action="palette-collapse" aria-label="${collapsed ? 'Expandir' : 'Contraer'} paleta" aria-expanded="${!collapsed}" title="${collapsed ? 'Expandir paleta' : 'Contraer paleta'}">${collapsed ? '⌃' : '⌄'}</button>
    <div class="palette-heading"><div><p class="panel-label">PALETA DE COLORES</p><span>Elige un color para pintar</span></div><div class="palette-view-toggle" aria-label="Vista de colores"><button type="button" data-action="palette-view" data-view="grid" class="${view === 'grid' ? 'active' : ''}" aria-label="Vista en cuadrícula" title="Cuadrícula">▦</button><button type="button" data-action="palette-view" data-view="list" class="${view === 'list' ? 'active' : ''}" aria-label="Vista en lista" title="Lista">☷</button></div></div>
    <div class="palette-groups" role="tablist" aria-label="Grupos de colores"><button type="button" data-action="palette-group" data-group="basics" class="${group === 'basics' ? 'active' : ''}" role="tab" aria-selected="${group === 'basics'}">Básicos <small>${BASIC_COLORS.length}</small></button><button type="button" data-action="palette-group" data-group="presets" class="${group === 'presets' ? 'active' : ''}" role="tab" aria-selected="${group === 'presets'}">Todos <small>${PRESET_COLORS.length}</small></button><button type="button" data-action="palette-group" data-group="custom" class="${group === 'custom' ? 'active' : ''}" role="tab" aria-selected="${group === 'custom'}">Personalizados <small>${personal.length}</small></button></div>
    <div class="palette-filters"><label class="palette-search"><span aria-hidden="true">⌕</span><input id="palette-search" type="search" value="${escapeText(query)}" placeholder="Buscar nombre o HEX..." aria-label="Buscar color por nombre o código HEX" /></label>${group === 'presets' ? `<div class="palette-category-picker"><button type="button" class="palette-category-trigger" data-action="palette-category-toggle" aria-haspopup="listbox" aria-expanded="${categoryOpen}">${escapeText(category)} <span aria-hidden="true">⌄</span></button><div class="palette-category-menu" role="listbox" aria-label="Categorías de color" ${categoryOpen ? '' : 'hidden'}>${categoryOptions}</div></div>` : ''}</div>
    ${group === 'custom' ? '<button type="button" class="button secondary full color-create-button" data-action="select-color">＋ Seleccionar color</button>' : ''}
    <div class="palette-swatches ${view}" role="listbox" aria-label="${group === 'custom' ? 'Colores personalizados' : group === 'basics' ? 'Colores básicos' : 'Colores predeterminados'}">${swatches || (group === 'custom' ? '<p class="palette-empty">Aún no has creado colores. Pulsa “Seleccionar color” para añadir uno.</p>' : '')}</div>
    ${group !== 'custom' ? '<button type="button" class="text-button color-create-link" data-action="select-color">＋ Crear color personalizado</button>' : ''}
    <div class="properties"><p class="panel-label">TAMAÑO DEL PATRÓN</p><div class="size-row"><label>Ancho<input id="resize-width" type="number" min="1" max="${maxDimension}" value="${pattern.width}" /></label><label>Largo<input id="resize-height" type="number" min="1" max="${maxDimension}" value="${pattern.height}" /></label></div><button class="button secondary full" data-action="resize">Aplicar tamaño</button><p class="hint">Reducir el patrón puede eliminar mostacillas del área recortada.</p></div>
  </aside>`;
}
